### ISSUE TITLE
Shaylen Naidoo: Conditional Send Should Support Logical Operations

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/Mailman#168]
**Email**
shaylen.naidoo@edmonton.ca

**Description**
Allow sending of mail merges to use several logical conditions such that we can use operations like AND, OR and NOT to join the multiple logical conditions.

**Comment by dchenier** [comment]
This is now possible in Rich Text Mailman, because all of the fields are rendered using the Handlebars templating engine. (to, cc, bcc, subject, body, and condition)

For example, If you have two columns "My Condition 1" and "My Condition 2":
To only send emails when both are TRUE use **{{#and [My Condition 1] [My Condition 2]}}**
To send emails if either are TRUE use **{{#or [My Condition 1] [My Condition 2]}}**

More powerful logical operators exist, documentation will be forthcoming
